# Generated by Django 5.1.6 on 2025-02-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Booking', '0002_alter_room_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR')], default='USD', max_length=10),
        ),
    ]
