# Generated by Django 5.1.4 on 2025-02-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Booking', '0003_alter_room_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pricePerNight',
            field=models.IntegerField(default=150),
        ),
    ]
