# Generated by Django 5.1.4 on 2025-02-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Booking', '0005_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupiedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupiedDates', to='Room_Booking.room')),
            ],
        ),
    ]
